#!/bin/sh
# Check to see if we are on master branch. Stop accidental commits
if [ $(git symbolic-ref HEAD 2>/dev/null) == "refs/heads/master" ]; then
	# Allows us to read user input below
	exec < /dev/tty

	while true; do
		read -p "You are on the master branch, are you sure you want to commit? (y/N)> " commit
		if [ "$commit" == "" ]; then
			commit="n"
		fi
		case $commit in
			[Yy] ) exit 0;;
			[Nn] ) exit 1;;
			* ) echo "Please answer y or no for yes or no?";;
		esac
	done
fi
exit 0
